
package com.email.soap.provider;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EMailSender", targetNamespace = "http://www.soap.email.com/provider/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EMailSender {


    /**
     * 
     * @param psendEMail
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.soap.email.com/provider/sendEMail")
    @WebResult(name = "soapString", targetNamespace = "http://www.soap.email.com/provider/", partName = "emailResponse")
    public String sendEMail(
        @WebParam(name = "eSoapEmailMessage", targetNamespace = "http://www.soap.email.com/provider/", partName = "psendEMail")
        SoapEmailMessage psendEMail);

}
