
package com.email.soap.provider;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EMailSenderService", targetNamespace = "http://www.soap.email.com/provider/", wsdlLocation = "file:/C:/Users/Sid/Desktop/MScomputerScience/Workspaces/EclipseJunoWorkspace/SpringWorkspace/bas-att-mvc/src/main/webapp/bas-email.wsdl")
public class EMailSenderService
    extends Service
{

    private final static URL EMAILSENDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMAILSENDERSERVICE_EXCEPTION;
    private final static QName EMAILSENDERSERVICE_QNAME = new QName("http://www.soap.email.com/provider/", "EMailSenderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Sid/Desktop/MScomputerScience/Workspaces/EclipseJunoWorkspace/SpringWorkspace/bas-att-mvc/src/main/webapp/bas-email.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMAILSENDERSERVICE_WSDL_LOCATION = url;
        EMAILSENDERSERVICE_EXCEPTION = e;
    }

    public EMailSenderService() {
        super(__getWsdlLocation(), EMAILSENDERSERVICE_QNAME);
    }

    public EMailSenderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMAILSENDERSERVICE_QNAME, features);
    }

    public EMailSenderService(URL wsdlLocation) {
        super(wsdlLocation, EMAILSENDERSERVICE_QNAME);
    }

    public EMailSenderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMAILSENDERSERVICE_QNAME, features);
    }

    public EMailSenderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EMailSenderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EMailSender
     */
    @WebEndpoint(name = "EMailSenderPort")
    public EMailSender getEMailSenderPort() {
        return super.getPort(new QName("http://www.soap.email.com/provider/", "EMailSenderPort"), EMailSender.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EMailSender
     */
    @WebEndpoint(name = "EMailSenderPort")
    public EMailSender getEMailSenderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.soap.email.com/provider/", "EMailSenderPort"), EMailSender.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMAILSENDERSERVICE_EXCEPTION!= null) {
            throw EMAILSENDERSERVICE_EXCEPTION;
        }
        return EMAILSENDERSERVICE_WSDL_LOCATION;
    }

}
